name: TypeCheck and Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Copy Configurations
        run: cp ./data/api-example.json ./data/api.json

      - name: Check Project
        run: bun run lint
